<link rel="stylesheet" href="css/contact.css">
<link rel="stylesheet" href="css/content.css">
<link rel="stylesheet" href="css/cv.css">
<link rel="stylesheet" href="css/footer.css">
<link rel="stylesheet" href="css/garageSwitcher.css">
<link rel="stylesheet" href="css/globaleStyle.css">
<link rel="stylesheet" href="css/heroSection.css">
<link rel="stylesheet" href="css/marqueeStrips.css">
<link rel="stylesheet" href="css/namePlate.css">
<link rel="stylesheet" href="css/noise.css">
<link rel="stylesheet" href="css/projects.css">
<link rel="stylesheet" href="css/responsiveMobile.css">
<link rel="stylesheet" href="css/responsiveTablet.css">
<link rel="stylesheet" href="css/sectionLayout.css">